### ISSUE TITLE
Make 'record-coverage' optional

### ISSUE THREAD

**Issue by martong** [Xazax-hun/csa-testbench#30]
The cc1 option `-record-coverage` causes huge overhead on Disk io, resulting CPUs in a stalling state and making the analysis 5x slower. This is problematic in CI jobs, where we just want to check if the analysis did not crash.

Perhaps the default behavior should not allow coverage recording and a command line flag should enable it only?

This is a quick fix now we are using:
https://github.com/martong/csa-testbench/commit/22a2d841544be603aa5afe34ae74c7f47453210b

**Comment by Xazax-hun** [comment]
Should be fixed in https://github.com/Xazax-hun/csa-testbench/commit/2728f7fd56f9751e364dc2340551fcb0c7d63208

**Comment by martong** [comment]
Thank you!
