### ISSUE TITLE
Unreachable should be handled as an assertion

### ISSUE THREAD

**Issue by martong** [Xazax-hun/csa-testbench#36]
Unfortunately, `llvm_unreachable` does not generate the `Assertion` text.
E.g.:
```
UNREACHABLE executed at /var/jenkins_home/workspace/ctu_pipeline_clang8/llvm/tools/clang/lib/Basic/SourceManager.cpp:2039!
```

**Comment by Xazax-hun** [comment]
Should be fixed in https://github.com/Xazax-hun/csa-testbench/commit/dadf9fecac02fb087770defb88a0072565b5f63c Could you test and close this in case it is resolved?

**Comment by martong** [comment]
Tested, thanks!
