### ISSUE TITLE
Warnings should be counted not only in case of failures

### ISSUE THREAD

**Issue by martong** [Xazax-hun/csa-testbench#37]
Currently we create statistics about warnings only if the analysis of a file failed. We should do that even if the analysis is successful.

**Comment by Xazax-hun** [comment]
Should be fixed in https://github.com/Xazax-hun/csa-testbench/commit/c5662577608030f3753c924a9e8db5b441856303  . Can you check?

**Comment by martong** [comment]
Started to test. Please get back to me if I forgot to report the results.

**Comment by martong** [comment]
Looks okay.
