### ISSUE TITLE
Support Clang instances with absolute path in the config file

### ISSUE THREAD

**Issue by martong** [Xazax-hun/csa-testbench#42]
There are many cases where we'd like to measure with two different Clang instances, each of them in a different path. E.g. when we want to compare statistics of Clang-9 vs Clang-10 but with the very same set of command line options. AFAIU it is not possible currently, is it?

**Comment by Xazax-hun** [comment]
It should be supported by the `clang_path` config option in configurations. Let me know if that does not work as intended.

**Comment by martong** [comment]
Yeah, that's missed my attention. Thanks!
