### ISSUE TITLE
Report into a self-contained document

### ISSUE THREAD

**Issue by martong** [Xazax-hun/csa-testbench#46]
I was wondering if it would be possible to report the statistics and the charts into a static self-contained html, i.e. which displays nicely in any browser without the need to download extra python packages.

Or even better, could we generate a pdf file as a report?

**Comment by Xazax-hun** [comment]
Could you check what parts of the HTML are not self contained? It does have some outgoing links to CodeChecker, but there should not be any python or other requirement to view the HTML. If there is any, that is a bug.

**Comment by martong** [comment]
My, bad I just realized that I have to use the `Zip` link in the top right corner to download a properly self-contained zipped webpage. Previously I tried with Chrome's `Save page as` menu item, that failed (and still fails).

![image](https://user-images.githubusercontent.com/5887427/121562722-02cecd80-ca1a-11eb-988e-094bb50c78e2.png)
