### ISSUE TITLE
streaming output for run_command

### ISSUE THREAD

**Issue by steakhal** [Xazax-hun/csa-testbench#48]
Sometimes, a `configure_command` and `make_command` takes a while to execute.
In these cases, it would be valuable to stream the output to somewhere.
Maybe poll them periodically.

What do you think?

**Comment by Xazax-hun** [comment]
Do you want to see it on the standard output or somewhere else is OK? You can always write those custom commands in a way that their output are piped into some files. 

In the long term, we might want to have an option where the output of all commands are going into a rotated log file (thus it avoids extensive growth) with an option to turn off rotation.

**Comment by steakhal** [comment]
What about merging stderr to stdout, and polling that stream.
That way it would print every message, regardless if that `run` succeeds or not.
In most CI systems, having logs quite is often beneficial.

**Comment by Xazax-hun** [comment]
> What about merging stderr to stdout, and polling that stream.

And where do you want to display it? I think having a clean std out is a feature (at least by default). This is why I prefer a rotated log file.

**Comment by steakhal** [comment]
I'm gonna reopen it if I have a proven concept about this.
